services:
  dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: dev_container
    working_dir: /app/code
    ports:
      - "8080:80"
      - "${REACT_APP_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - ./:/app
      - ./docker/dev/config/dev/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - VITE_PORT=${VITE_PORT:-5173}
      - DB_HOST=pgsql
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
      - POSTGRES_PORT=5432
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/dev/config/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      pgsql:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_container
    ports:
      - "8025:8025"

volumes:
  pg_data:
